# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01db01c2757e75221d9de2eb0d1ad0806c1966370eeed6a660eb3fde719fb3085828b36dab9fbdea19c56bb0ec6e6f797b6aec626ec16fe58cab01a8095096ea

test:
  secret_key_base: 3ab49086233acff4d04bad637d36163fe9afb4cdf68dd374f953e57f208aa0b1639fb117e168f66373009211d8b15ee85158d66294e77c7ec470c7ab419a7f81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
